"""
auto_fix.py  --  ArduPilot parameter auto-fix engine

Given a diagnosed fault type + confidence + parameter warnings,
generates MAVProxy param set commands and a .param file so the
operator can apply corrections in one step rather than hunting through
the wiki manually.
"""

from __future__ import annotations
import os
from datetime import datetime
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Fix rules: fault_type -> list of (param_name, value, reason)
# ---------------------------------------------------------------------------
FIX_RULES: Dict[str, List[Tuple[str, float, str]]] = {
    "rc_failsafe": [
        ("FS_THR_ENABLE", 1, "Enable RC throttle failsafe (was disabled)"),
        ("FS_THR_VALUE",  975, "Failsafe trigger below 975 us"),
    ],
    "battery_failsafe": [
        ("BATT_FS_LOW_ACT",  1, "Set low-battery failsafe action to RTL"),
        ("BATT_FS_CRT_ACT",  2, "Set critical-battery failsafe action to Land"),
        ("BATT_LOW_VOLT",   10.5, "Low voltage threshold for 3S LiPo"),
        ("BATT_CRT_VOLT",    9.9, "Critical voltage threshold for 3S LiPo"),
    ],
    "ekf_failsafe": [
        ("EK2_CHECK_SCALE", 100, "Restore EKF innovation check scale to 100 percent"),
        ("FS_EKF_THRESH",   0.8, "Raise EKF failsafe threshold to 0.8"),
        ("FS_EKF_ACTION",     1, "Set EKF failsafe action to Land"),
    ],
    "gps_glitch": [
        ("GPS_HDOP_GOOD",  2.0, "Require HDOP <= 2.0 before arming"),
        ("EK2_GPS_CHECK",   31, "Enable all EKF GPS health checks"),
        ("GPS_GNSS_MODE",    0, "Allow all GNSS constellations for better fix"),
    ],
    "compass_error": [
        ("COMPASS_USE",       1, "Re-enable primary compass"),
        ("COMPASS_AUTODEC",   1, "Enable automatic declination"),
        ("COMPASS_MOTCT",     2, "Enable motor interference compensation"),
    ],
    "vibration_fault": [
        ("INS_ACCEL_FILTER", 10, "Lower accel LPF to 10 Hz to reduce vibration noise"),
        ("INS_GYRO_FILTER",  20, "Lower gyro LPF to 20 Hz to reduce vibration noise"),
        ("ATC_ACCEL_P_MAX", 110000, "Limit pitch acceleration to reduce oscillation"),
        ("ATC_ACCEL_R_MAX", 110000, "Limit roll acceleration to reduce oscillation"),
    ],
    "baro_fault": [
        ("GND_TEMP",        25, "Set ground temperature calibration (degrees C)"),
        ("BARO_PROBE_EXT",   0, "Disable external barometer probing if faulty"),
    ],
    "motor_imbalance": [
        ("MOT_SPIN_ARM",  0.10, "Increase motor arm spin to 10 percent"),
        ("MOT_SPIN_MIN",  0.15, "Raise minimum spin to 15 percent"),
        ("MOT_THST_EXPO", 0.65, "Set thrust expo for typical propeller curve"),
    ],
}

UNIVERSAL_FIXES: List[Tuple[str, float, str]] = [
    ("ARMING_CHECK", 1, "Ensure all arming checks are enabled"),
    ("LOG_BITMASK",  65535, "Enable full logging for future diagnosis"),
]


def generate_fixes(
    fault_type: str,
    confidence: float,
    param_warnings: Optional[List[Dict]] = None,
    confidence_threshold: float = 0.60,
    include_universal: bool = True,
) -> Dict:
    result = {
        "fault_type": fault_type,
        "confidence": confidence,
        "applied": False,
        "mavproxy_commands": [],
        "param_file_lines": [],
        "summary": "",
    }

    if confidence < confidence_threshold:
        result["summary"] = (
            f"Confidence {confidence:.0%} is below threshold "
            f"{confidence_threshold:.0%}. No auto-fix applied."
        )
        return result

    fixes: List[Tuple[str, float, str]] = list(FIX_RULES.get(fault_type, []))

    if param_warnings:
        warned_params = {w.get("param") for w in param_warnings if w.get("param")}
        if warned_params:
            targeted = [f for f in fixes if f[0] in warned_params]
            if targeted:
                fixes = targeted + [f for f in fixes if f[0] not in warned_params]

    if include_universal:
        fixes.extend(UNIVERSAL_FIXES)

    header = (
        f"# ArduPilot auto-fix -- {fault_type} "
        f"(confidence {confidence:.0%}) -- {datetime.utcnow().strftime('%Y-%m-%dT%H:%MZ')}\n"
        f"# Generated by ardupilot-log-diagnosis/auto_fix.py\n"
    )
    param_lines = [header]
    mav_cmds = []

    for param_name, value, reason in fixes:
        mav_cmds.append(f"param set {param_name} {value}")
        param_lines.append(f"{param_name}\t{value}\t# {reason}")

    result["applied"] = True
    result["mavproxy_commands"] = mav_cmds
    result["param_file_lines"] = param_lines
    result["summary"] = (
        f"{len(fixes)} parameter fix(es) generated for {fault_type}. "
        f"Apply via MAVProxy or Mission Planner Full Parameter List."
    )
    return result


def write_param_file(fix_result: Dict, output_path: str) -> str:
    if not fix_result.get("applied"):
        return ""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as fh:
        fh.write("\n".join(fix_result["param_file_lines"]))
    return output_path


def print_fix_report(fix_result: Dict) -> None:
    print("\n" + "=" * 60)
    print("AUTO-FIX REPORT")
    print("=" * 60)
    print(f"Fault     : {fix_result['fault_type']}")
    print(f"Confidence: {fix_result['confidence']:.0%}")
    print(f"Status    : {'FIXES GENERATED' if fix_result['applied'] else 'SKIPPED (low confidence)'}")
    if fix_result["applied"]:
        print("\nMAVProxy commands:")
        for cmd in fix_result["mavproxy_commands"]:
            print(f"  {cmd}")
        print(f"\n{fix_result['summary']}")
    else:
        print(f"\n{fix_result['summary']}")
    print("=" * 60)
